### PR TITLE
Add some badges to README.md

### PR DESCRIPTION
**Pull request by brodybits**
I hope the image style of the badges are OK, will understand if they need to be changed.

### CODE REVIEW

**Comment by inovramadani** [comment]
Hello, I have question: is it possible to use react-primitives with electronJS?
https://stackoverflow.com/questions/59325461/can-react-primitives-be-used-in-electronjs-app

**Comment by alxhotel** [comment]
Ping @mathieudutour

**Comment by mathieudutour** [comment]
don't think any of those badges are useful

**Comment by brodybits** [comment]
I don't understand the disposition. I think all of the badges would be useful if someone looks at the npm page and has any interest in the information.

**Comment by mathieudutour** [comment]
There is already the license and the link to the repo showing on the npm page, not need for all the issues links

**Comment by brodybits** [comment]
The npm version badge would still be useful on GitHub, and I think others would appreciate it as well.

I just removed all of the other badges from this proposal. Do I have to open another PR for this to be considered?

**Comment by mathieudutour** [comment]
I really don't think it's useful, but if that's something that you can't live without update the PR with just the npm badge and the default style

**Comment by brodybits** [comment]
I just raised new PR with just the npm badge, with the default style I got from imgshields.io, since closed PR does not seem to take my updates. Thanks.

**Pull request closed without merging**
