### PR TITLE
 Fix upgrade to react-native-web@0.2.2

### PR DESCRIPTION
**Pull request by likethemammal**
Commit on top of https://github.com/lelandrichardson/react-primitives/pull/97 to have it pass the tests

### CODE REVIEW

**Comment by likethemammal** [comment]
This PR is on [npm](https://www.npmjs.com/package/@likethemammal/react-primitives) untill the react-native-web upgrade is in, as `@likethemammal/react-primitives`

**Comment by samjt** [comment]
@lelandrichardson could this be merged? Would be a very useful update.

**Comment by MoOx** [comment]
This package have a very light activity. You should not expect response until it's a BIG deal. Which doesn't seems to be the case.
Btw, RNW is already @0.3.1 this days...

**Comment by likethemammal** [comment]
It seems more important to ppl that rest of support for React 16 get in, rather than react-native-web get upgraded to the latest. Thats why I just focused on 0.2.2, like the other PR had

**Comment by sawa-zen** [comment]
It is awesome PR! I am waiting to be merged! 👍

**Pull request merged**
