### PR TITLE
Touchable: TouchableMixin wasn't injected in native

### PR DESCRIPTION
**Pull request by ktj**
Fixes:
https://github.com/lelandrichardson/react-primitives/issues/71
https://github.com/lelandrichardson/react-primitives/issues/75
https://github.com/lelandrichardson/react-primitives/issues/59

### CODE REVIEW

**Comment by ktj** [comment]
Doesn't work.
I think the problem may be that this uses UIManager from src/web/

**Comment by ktj** [comment]
Here is a built version that you can use before this gets approved.
"react-primitives": "ktj/primitives-build"

**Comment by ktj** [comment]
@lelandrichardson Any chance for this to be merged?

**Comment by theTechie** [comment]
Looking forward for this to be merged.

**Pull request closed without merging**
