### PR TITLE
Inject Touchable from react-native

### PR DESCRIPTION
**Pull request by Hermanya**
Fixing
`TypeError: undefined is not a function (evaluating 'this.touchableGetInitialState()')`

### CODE REVIEW

**Comment by Hermanya** [comment]
This failure is unrelated to the patch. 
Travis fails to build yoga-layout.

**Comment by mathieudutour** [comment]
Oh so that fixes #71? I got confused, I thought it was because of react 16.

Thanks!

**Comment by davidpett** [comment]
@mathieudutour @lelandrichardson Are there plans on a release to include this? please and thank you

**Comment by sawa-zen** [comment]
@mathieudutour @lelandrichardson I can't wait to release this! 😄 please and thank you

**Pull request merged**
