### PR TITLE
Fix React 16 for Web.

### PR DESCRIPTION
**Pull request by dmiller9911**
React 16 support for react-native-web was added in v0.1.0.  Update examples to use React 16.  Added Touchable Example to allow easy verification of Touchable.

### CODE REVIEW

**Comment by dmiller9911** [comment]
Missed the tests on this.  Do I need to fix them or can I delete the /web folder along with react-web.js injection?  They are no longer used since the switch to react-native-web.  Fixing the tests will only require some dep upgrades and pulling over setValueForStyle from react-native-web.

**Comment by episodeyang** [comment]
@dmiller9911 from the looks of it some of the modules are either completely gone or moved.

**Comment by ktj** [comment]
It's easier to just make a simple package that imports stuff from rnw, rn, vr, sketchapp (using platform-specific extensions) and exports the same stuff as primitives does.

That's at least what I did

**Comment by likethemammal** [comment]
React 16.2 and react-native-web 0.2.2 support added with the build passing in this PR: https://github.com/lelandrichardson/react-primitives/pull/98

For anyone looking for a working npm package, checkout [@likethemammal/react-primitives](https://www.npmjs.com/package/@likethemammal/react-primitives)

**Comment by dmiller9911** [comment]
closing since other PR's have been opened for this, and I am no longer using this package.

**Pull request closed without merging**
