### PR TITLE
Happo Test

### PR DESCRIPTION
**Pull request by lelandrichardson**

### CODE REVIEW

**Comment by lelandrichardson** [comment]
:lipstick: [Visual diffs or new examples were found](https://react-primitives-happo.s3-us-west-1.amazonaws.com/e5b1d64a9f0453febb155f0a013b0396/index.html) for 5b576efbf02befba0fe4d3716f87b43d3b571eca...c6842bd019ddc45b15900bb2328280237df2d978.

**Comment by lelandrichardson** [comment]
:lipstick: [Visual diffs or new examples were found](https://react-primitives-happo.s3-us-west-1.amazonaws.com/e732ec24ef3f6665678dfe25d0d9ea07/index.html) for 5b576efbf02befba0fe4d3716f87b43d3b571eca...c6842bd019ddc45b15900bb2328280237df2d978.

**Comment by lelandrichardson** [comment]
:lipstick: [Visual diffs or new examples were found](https://react-primitives-happo.s3-us-west-1.amazonaws.com/7c1a71f02d168158e9ff10e7b222d97f/index.html) for 5b576efbf02befba0fe4d3716f87b43d3b571eca...a7bcf6337f961f12ee1cea6b2941ad93e78b2105.

**Comment by ljharb** [comment]
@lencioni is there any easyish way to configure happo on a non-org repo so that the owner isn't the one posting the comments?

**Comment by lelandrichardson** [comment]
@ljharb i think you'd just have to create a public github account and use an access token for that account

**Comment by ljharb** [comment]
True, I guess only orgs can have bot users.

**Comment by lelandrichardson** [comment]
happo could move to an org (ie, `github.com/happo/happo`) or something, and then we could have happo be the bot....

**Comment by lencioni** [comment]
Happo is currently in the Galooshi org.

**Pull request closed without merging**
