### PR TITLE
upgrade react-native-web@0.2.2

### LINKED ISSUE #84: React 16 Support
Currently this is blocked on an upstream dependency, `react-native-web` - they're tracking this at https://github.com/necolas/react-native-web/issues/364

When trying to run against react@16.0.0-beta.5, it looks like:
```
Error: Cannot find module 'react-dom/lib/EventPluginHub'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/-/Code/zendesk/protoloop-4/node_modules/react-native-web/dist/modules/injectResponderEventPlugin/index.js:1:83)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

### PR DESCRIPTION
**Pull request by theTechie**
This will probably fix #84 and #95

### CODE REVIEW

**Comment by mattborn** [comment]
@theTechie Trying this out now…

**Comment by mattborn** [comment]
Trying to use these changes resulted in the following when attempting to render to Sketch:

**Comment by theTechie** [comment]
looks like its already taken care of in the [latest release](https://github.com/necolas/react-native-web/blob/0.2.2/src/modules/injectResponderEventPlugin/index.js)

**Comment by mattborn** [comment]
You’re right. I wasn’t sure if the react and react-dom versions being different (15.4 vs. 16.x) is still causing these sorts of errors. I am trying to use `react-primitives` with targets that all use React 16.x and I have yet to find a combination of versions that works in all—react-dom, react-native, and react-sketchapp. Like you, my hunch was upgrading react-native-web would solve it, but it doesn’t. 

@theTechie Do you know if there is a reason why react-primitives should not also [upgrade to React 16 like react-native-web](https://github.com/necolas/react-native-web/blob/master/package.json#L100-L102)?

**Comment by theTechie** [comment]
We are on the same ship :-) 

> Do you know if there is a reason why react-primitives should not also upgrade to React 16 like react-native-web?

That's my next quest this week

**Comment by ktj** [comment]
@theTechie @mattborn 
I recommend creating a new project and use platform specific extensions to import/export required stuff from rn, rnw, sketchapp.

If you are using styled-components (like I do), then you can also easily create a wrapper that uses your own project instead of react-primitives. You don't have to change existing code to make this work in your project. You can use example babel module resolver.

Example for .babelrc

```
{
  "presets": ["es2015", "react"],
  "plugins": [
  	"transform-class-properties",
  	"transform-object-rest-spread",
  	"lodash",
  	["module-resolver", {
      "alias": {
        "^react-primitives$": "react-brimitives",
        "styled-components/primitives": "styled-brimitives"
      }
    }]
  	]
}
```

**Comment by necolas** [comment]
FYI, you lose a lot of performance wrapping RN/RNW with styled-components

**Comment by ktj** [comment]
Looks like so.
Thanks for the tip

nayttokuva 2018-1-11 kello 9 30 23
(ran benchmarks from rnw project)

**Comment by likethemammal** [comment]
Pulled down this fork and ran the build and tests. Still needed a few changes before the tests passed.

Created a new fork from this one and added a commit to fix the issues and get the build passing

PR includes @theTechie commits and my own: https://github.com/lelandrichardson/react-primitives/pull/98

**Pull request merged**
